### ISSUE TITLE
Feature request : other types of gradients

### ISSUE THREAD

**Issue by sachaarbonel** [JonathanMonga/flutter_gradients#2]
Hi @JonathanMonga , thank's for this great library. Could you bring support for other types of gradients like Sweep, Radial etc ?

**Comment by JonathanMonga** [comment]
Yes, i can add that in the library.
If you want to contribute don't hesitate.

**Comment by JonathanMonga** [comment]
It supports right now two other gradient types.

**Comment by sachaarbonel** [comment]
Thank's a lot :+1:
