### ISSUE TITLE
Possibility to set tileMode

### ISSUE THREAD

**Issue by abianche** [JonathanMonga/flutter_gradients#3]
It seems that all the gradients are created with TileMode.repeated. However, in many cases this is not ideal, and in general it should be configurable.

See: https://api.flutter.dev/flutter/painting/LinearGradient/tileMode.html

**Comment by JonathanMonga** [comment]
Yes, tileMode = TileMode.repeated,
I will make it configurable.

**Comment by JonathanMonga** [comment]
I fix it.
you can right now change this parameter in the method.
